server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

database:
  url: "jdbc:postgresql://localhost:5432/rinha"
  user: "postgres"
  password: "secret"